In [12]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

# Question 1
Answer : Yes, there is a differnece in the datatypes of variables list_ and array_list. 
        
        list_ - It is a simple python list object.
        array_list - It ia a numpy array object.

In [13]:
type(list_)

list

In [14]:
type(array_list)

numpy.ndarray

# Question 2
Answer : Code to print datatype of every elements in list_ and array_list

In [15]:
# Code to print datatype of every elements in list_
for i in list_ :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [16]:
# Code to print datatype of every elements in array_list
for i in array_list : 
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Question 3
Answer : 

In [17]:
array_list = np.array(object = list_, dtype = int)

Yes there will be difference in the datatype of elements in list_ and array_list. 

        In list_ every element remians string dtype but now in array_list the dtype of each element changes to int64.

In [19]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [20]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Part 2

In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Question 4
Answer : 

In [23]:
# (i) Code to find shape of num_array
print("Shape of num_array : ",num_array.shape)

Shape of num_array :  (2, 3)


In [24]:
# (ii) Code to find size of num_array
print("Size of num_array : ",num_array.size)

Size of num_array :  6


# Question 5
Answer : Code to create a matrix of 3*3 containing zeroes only.

In [34]:
zeroes_array = np.zeros((3,3))

In [35]:
print(zeroes_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Question 6
Answer : Code to create a 5*5 identity matrix 

In [43]:
id_matrix = np.eye(5,dtype = int)

In [44]:
print(id_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
